# Generated by Django 4.1.5 on 2023-04-04 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=64)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField()),
                ('repetitions', models.IntegerField()),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.routine')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.workout')),
            ],
        ),
        migrations.AddField(
            model_name='routine',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.workout'),
        ),
    ]
