# Generated by Django 4.1.5 on 2023-04-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_routine_workout_workoutroutine_routine_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.TextField(blank=True, default='', max_length=128),
        ),
    ]
