# Generated by Django 4.1.5 on 2023-04-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_workout_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='name',
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64, unique=True),
        ),
    ]
