# Generated by Django 4.1.5 on 2023-04-04 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_routine_workout_routine_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutroutine',
            options={'verbose_name': 'Workout Routine', 'verbose_name_plural': 'Workout Routines'},
        ),
    ]
