# Generated by Django 4.1.5 on 2023-04-19 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_workoutroutine_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workoutroutine',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.routine'),
        ),
        migrations.AlterField(
            model_name='workoutroutine',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.workout'),
        ),
    ]
